services:
  strapi:
    build: ./backend
    image: ss-strapi-image
    container_name: ss-strapi-backend
    ports:
      - "1337:1337"
    env_file: ./.env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./backend/config:/opt/app/config  # Fixed path
      - ./backend/src:/opt/app/src        # Fixed path
      - ./backend/public/uploads:/opt/app/public/uploads  # Fixed path
      - strapi_node_modules:/opt/app/node_modules # Named volume for node_modules
    restart: unless-stopped
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    restart: unless-stopped
    env_file: ./.env
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - "5432:5432"
    networks:
      - strapi

  frontend:
    build: ./frontend
    image: ss-frontend-image # Good practice: Give your image a name
    container_name: ss-react-frontend # Good practice: Explicit container names
    ports:
      - "3000:80"
    depends_on:
      - strapi
    volumes:
      - ./frontend/src:/usr/src/app/src  # Corrected path:  Consistent with frontend structure
      - frontend_node_modules:/usr/src/app/node_modules # Named volume for node_modules
    environment: # add the strapi url here as well, for best practices
      - STRAPI_URL=http://strapi:1337
      - NODE_ENV=development
volumes: # Define named volumes at the top level
    strapi-data:
    strapi_node_modules:
    frontend_node_modules:
networks:
  strapi:
    name: Strapi
    driver: bridge
