version: '3.8'

services:
  strapi:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      NODE_ENV: development
    restart: unless-stopped